using Proxytrace.Domain.AgentCall;
using Nordstein.Core.AI.Messages;
using Proxytrace.Storage.Internal.Entities.Inference;

namespace Proxytrace.Storage.Internal.Entities.AgentCall;

[StoredDomainEntity(typeof(IAgentCall))]
internal record AgentCallEntity : Entity
{
    /// <summary>
    /// FK to the agent version active when this call was made. Joins to AgentVersionEntity to resolve
    /// the agent and project. Maps to the agent_calls.agent_version_id column.
    /// </summary>
    public required Guid AgentVersionId { get; init; }
    /// <summary>
    /// FK to the model endpoint the request was routed to (provider + model + pricing). Maps to
    /// the agent_calls.endpoint_id column.
    /// </summary>
    public required Guid EndpointId { get; init; }
    /// <summary>
    /// The full inbound conversation (system message plus user turns) serialized as JSON. This is the
    /// authoritative request payload; RequestPreview is a denormalized excerpt for list queries.
    /// </summary>
    public required Conversation Request { get; init; }
    /// <summary>
    /// The assistant response message serialized as JSON, or null when the call errored before
    /// the provider returned a response.
    /// </summary>
    public required AssistantMessage? Response { get; init; }
    /// <summary>
    /// Number of non-cached prompt tokens billed by the provider, or null when the provider did
    /// not return usage data (e.g. streaming errors).
    /// </summary>
    public required ulong? InputTokens { get; init; }
    /// <summary>
    /// Number of completion tokens generated by the provider, or null when usage was not reported.
    /// </summary>
    public required ulong? OutputTokens { get; init; }
    /// <summary>
    /// Number of prompt tokens served from the provider's prompt cache, or null when caching is
    /// unsupported or usage was not reported.
    /// </summary>
    public required ulong? CachedInputTokens { get; init; }
    /// <summary>
    /// End-to-end round-trip time in milliseconds measured at the proxy, or null when the call
    /// errored before a response arrived.
    /// </summary>
    public required double? LatencyMs { get; init; }
    /// <summary>
    /// HTTP status code returned to the caller — 2xx for success, 4xx/5xx for provider or proxy errors.
    /// Used by the error-rate aggregation and the HTTP status filter.
    /// </summary>
    public required int HttpStatus { get; init; }
    /// <summary>
    /// The provider's finish_reason string (e.g. "stop", "tool_calls", "length"), or null when the
    /// call did not complete successfully.
    /// </summary>
    public required string? FinishReason { get; init; }
    /// <summary>
    /// Human-readable error description when the call failed at the proxy or provider layer, null
    /// on success. Stored for display in the trace detail view.
    /// </summary>
    public required string? ErrorMessage { get; init; }
    /// <summary>
    /// JSON-serialized inference parameters (temperature, top-p, etc.) that were in effect for this
    /// call, captured at ingestion time. Maps to the agent_calls.model_parameters column.
    /// </summary>
    public required ModelParametersData ModelParameters { get; init; }
    /// <summary>
    /// Groups this call with others in the same logical conversation thread. Nullable and FK-free —
    /// revocation of a conversation never cascades away telemetry.
    /// </summary>
    public required Guid? ConversationId { get; init; }
    /// <summary>
    /// Groups this call with others originating from the same proxy session (identified by the
    /// caller-supplied external key). Nullable and FK-free — session deletion never cascades away telemetry.
    /// </summary>
    public required Guid? SessionId { get; init; }

    // The inbound Proxytrace API key this call authenticated with, or null when unattributable (the
    // upstream-key auth path, or any row written before key attribution existed). Deliberately
    // FK-free — like SessionId/ConversationId — so revoking a key never cascades away telemetry.
    // Backs the per-key cost breakdown and key-scoped budgets.
    /// <summary>
    /// The Proxytrace API key this call authenticated with, or null when unauthenticated via key or
    /// when the row predates key attribution. FK-free so key revocation never removes telemetry.
    /// </summary>
    public Guid? ApiKeyId { get; init; }

    // Outlier characteristics flagged at ingestion (bitmask). 0 = not an outlier. Persisted as a
    // single byte; a partial index (see AgentCallConfig) serves the "outliers only" trace filter.
    /// <summary>
    /// Bitmask of anomaly characteristics detected at ingestion time (high latency, high token count,
    /// error, etc.). Zero means no outlier flags. A partial index covers non-zero values for the
    /// outliers-only trace filter.
    /// </summary>
    public OutlierFlags OutlierFlags { get; init; }

    // Denormalised summaries populated at write time so the traces-list query can project scalar
    // columns only, without reading/deserialising the Request and Response payload columns.
    /// <summary>
    /// Truncated first user message from the request, populated at write time so list queries can
    /// display a preview without deserializing the full Request JSON payload.
    /// </summary>
    public string? RequestPreview { get; init; }
    /// <summary>
    /// Number of tool-call requests contained in the assistant response, denormalized at write time
    /// for the ToolCount sort and display in the traces list.
    /// </summary>
    public int ResponseToolRequestCount { get; init; }

    // Denormalised at write time so token/cache sorts and range filters hit plain indexed columns
    // instead of per-row expressions. Null when the call reported no usage.
    /// <summary>
    /// Sum of InputTokens and OutputTokens, denormalized at write time so the total-token sort and
    /// min/max token filters execute as indexed column comparisons rather than computed expressions.
    /// </summary>
    public ulong? TotalTokens { get; init; }
    /// <summary>
    /// Fraction of input tokens served from the provider's cache (CachedInputTokens / InputTokens),
    /// denormalized at write time to allow indexed sorting by cache efficiency in the traces list.
    /// </summary>
    public double? CacheHitRate { get; init; }

    // One row per distinct tool name requested in the response — backs the ToolName filter's EXISTS
    // semi-join and the project-scoped tool-name picker. See AgentCallToolEntity/AgentCallToolConfig.
    /// <summary>
    /// Child rows indexing the distinct tool names present in the response, one row per name. Backs
    /// the ToolName filter (EXISTS semi-join) and the project-scoped tool-name picker.
    /// </summary>
    public List<AgentCallToolEntity> Tools { get; init; } = [];
}
